CHANGELOG.md
README.md
composer.json
lib/Exporter/Source/DoctrineODMQuerySourceIterator.php
lib/Exporter/Source/DoctrineORMQuerySourceIterator.php
lib/Exporter/Source/PropelCollectionSourceIterator.php

Symfony 2.2 support drop as this version is not supported anymore.
Must be tag as a new minor version (e.g. `1.4`)

Fix deprecated PropertyAccess::getPropertyAccessor usage

---

lib/Exporter/Source/XmlSourceIterator.php
test/Exporter/Test/Source/XmlSourceIteratorTest.php

Add possibility to set custom tag names for the XmlSourceIterator.
e.g: Can be used to parse files like this : 
```xml
<?xml version="1.0" ?>
<channel>
<item>
...
</item>
<item>
...
</item>
</channel>
```
by passing tag names to the constructor
```php
$source = new XmlSourceIterator($filename, 'channel', 'item');
```
No BC Break as the default values for the tag names are `datas`and `data`.
ping @Soullivaneuh @rande

[XmlSourceIterator] Add possibility to set custom tag names

---

lib/Exporter/Writer/JsonWriter.php

It should be a resource, not a string.

Fix wrong PHPDoc type on JsonWriter::$file

---

composer.json
docs/reference/outputs.rst
src/Writer/CsvWriter.php
src/Writer/JsonWriter.php
src/Writer/TypedWriterInterface.php
src/Writer/XlsWriter.php
src/Writer/XmlWriter.php
test/Writer/AbstractTypedWriterTestCase.php
test/Writer/CsvWriterTest.php
test/Writer/JsonWriterTest.php
test/Writer/XlsWriterTest.php
test/Writer/XmlWriterTest.php

```markdown
- `MimeTypedWriterInterface` can be implemented to indicate the suitable `Content-Type` header and format for a writer.
```
This PR allows us to avoid [this kind of thing](https://github.com/sonata-project/SonataCoreBundle/blob/3.x/Exporter/Exporter.php#L37)

When applicable, provide mime type

---

UPGRADE-1.x.md
src/Test/AbstractTypedWriterTestCase.php
test/Writer/AbstractTypedWriterTestCase.php

I am targetting this branch, because this is BC.
```markdown
- Deprecate `Test\Writer\AbstractTypedWriterTestCase` in favor of `Test\AbstractTypedWriterTestCase`
```
Use the correct namespace for abstract TestCases, so they will be loaded when excluding the tests directory in the (non dev-)autoloader.

Use correct namespace for custom phpunit test cases

---

test/Writer/CsvWriterTest.php
test/Writer/JsonWriterTest.php
test/Writer/XlsWriterTest.php
test/Writer/XmlWriterTest.php

I am targetting this branch, because this is BC
```markdown
- Use recommended `AbstractTypedWriterTestCase` class in tests
```
Since deprecation of previous `AbstractTypedWriterTestCase` class, exporter unit tests should now use recommended class.

Use recommended AbstractTypedWriterTestCase class in tests

---

composer.json
docs/index.rst
docs/reference/symfony.rst
src/Bridge/Symfony/Bundle/SonataExporterBundle.php
src/Bridge/Symfony/DependencyInjection/Compiler/ExporterCompilerPass.php
src/Bridge/Symfony/DependencyInjection/Configuration.php
src/Bridge/Symfony/DependencyInjection/SonataExporterExtension.php
src/Bridge/Symfony/Resources/config/services.xml
src/Exporter.php
test/Bridge/Symfony/DependencyInjection/ConfigurationTest.php
test/Bridge/Symfony/DependencyInjection/ExporterCompilerPassTest.php
test/Bridge/Symfony/DependencyInjection/SonataExporterExtensionTest.php
test/ExporterTest.php

I am targetting this branch, because this is a fully BC feature
Closes #118 
```markdown
- Added `Exporter\Exporter` class to provide a Symfony `StreamedResponse`.
- Added a `sonata.exporter.exporter` service to deprecate the one defined in the admin bundle
```
This PR imports the exporter class defined in SonataCoreBundle, and the service defined in the admin bundle, making it configurable in the process.

Add exporter service

---

src/Exporter.php
test/ExporterTest.php

I am targetting this branch, because this is backwards-compatible
```markdown
- Added some `Exporter::getAvailableFormats` to retrieve the list of the formats of the registered writers
```
Nothing, I hope
I'd like to make the admin bundle more flexible about exports, and this method should allow us to have the export formats list nicely update each time we add a new writer.

Advertise export formats

---

src/Exporter.php

Make \Exporter\Exporter::addWriter public.
This will fix Symfony embedded bundle since we call this function to create default sonata.exporter.exporter service.
Plus, it could be useful to have it public.

Make \Exporter\Exporter::addWriter public

---

src/Source/DoctrineODMQuerySourceIterator.php
src/Source/DoctrineORMQuerySourceIterator.php
src/Source/PropelCollectionSourceIterator.php

I am targeting this branch, because there are no BC breaks.
```markdown
- Allow `\DateTimeImmutable` values
```
This PR changes value type checking from `instanceof \DateTime` to `instanceof \DateTimeInterface`, which allows `\DateTimeImmutable` values to be exported correctly. Previously, this would cause a fatal error "Object of class DateTimeImmutable could not be converted to string at vendor/sonata-project/exporter/src/Source/DoctrineORMQuerySourceIterator.php:161)".

Replace type checking of DateTime with DateTimeInterface

---

UPGRADE-2.0.md
composer.json

I am targeting this branch, because this is a php major version bump.
```markdown
- support for php 5.6 - 7.1
```

Make php 7.1 requirement explicit

---

src/Writer/CsvWriter.php
tests/Writer/CsvWriterTest.php

I am targeting this branch, because this is not BC breaking, just a breakfix.
Closes #219 
- CsvWriter actually uses the escape parameter.
Simplified version of the PR to just fix the missing params.

[Bug] Actually use the escape parameter.

---

src/Writer/CsvWriter.php
src/Writer/CsvWriterTerminate.php
tests/Writer/CsvWriterTerminateTest.php
tests/Writer/CsvWriterTest.php

I am targeting this branch, because this is not BC breaking.
```markdown
- Added support for custom terminators with `CsvWriter` class
```
A small feature addition to aid in the output of CSVs that are to be parsed by old/faulty programs/automation (mostly Microsoft). For example, if it's a program expecting "\r\n" for each line, it may only get the first line of the CSV and stop. Being able to control/manipulate the termination string (aka EOL) is pretty important for legacy support.

Support custom CSV termination.

---

src/Bridge/Symfony/Resources/config/services.xml

I am targeting this branch, because this is a hotfix..
```markdown
- Made `sonata.exporter.exporter` service public
```
This service needs to be public to use it with symfony 4.

Make exporter public

---

src/Bridge/Symfony/Resources/config/services.xml

I am targeting this branch, because `Exporter` class was not autowired.
Closes #244 
```markdown
Provide autowiring of `Exporter` class
```
Add `sonata.exporter.exporter` alias of `Exporter` class and allow autowire to it.

Provide autowiring for Exporter class

---

src/Bridge/Symfony/Bundle/SonataExporterBundle.php
src/Bridge/Symfony/Resources/config/services.xml

The `Exporter\*` namespace does not exist.
I am targeting this branch, because this is a bugfix.
```markdown
- Fixed wrong namespace usage
```

Fixed wrong namespace

---

src/Exporter.php
src/Writer/WriterInterface.php
src/Writer/XmlExcelWriter.php

I am targeting this branch, because it's no longer an issue with the 2.x branch
Fix type error:
Type error: Argument 2 passed to MyApp\Exporter\EquipementHandler::create() must be an instance of Exporter\Writer\WriterInterface, instance of Sonata\Exporter\Writer\XlsWriter given
```markdown
- Fix namespace typo
```

Fix issue fix WriterInterface namespace

---

src/Bridge/Symfony/DependencyInjection/Configuration.php

This is to fix [deprecation for symfony/config 4.2+](https://symfony.com/blog/new-in-symfony-4-2-important-deprecations#deprecated-tree-builders-without-root-nodes) as in https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/871
```markdown
- Fix deprecation for symfony/config 4.2+
```

Fix deprecation for symfony/config 4.2+

---

tests/Writer/GsaFeedWriterTest.php

I'm using Mac OS and I get this error on tests:
```
1) Sonata\Exporter\Tests\Writer\GsaFeedWriterTest::testSimpleWrite
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'/var/folders/48/fkmnn6gs2998gq8wc5f83d780000gn/T/sonata_exporter_test/feed_00001.xml'
+'/private/var/folders/48/fkmnn6gs2998gq8wc5f83d780000gn/T/sonata_exporter_test/feed_00001.xml'
```

Fix realpath on tests

---

src/Exception/InvalidDataFormatException.php
src/Exception/RuntimeException.php
src/Writer/CsvWriter.php
src/Writer/GsaFeedWriter.php
src/Writer/JsonWriter.php
src/Writer/SitemapWriter.php
src/Writer/WriterInterface.php
src/Writer/XmlExcelWriter.php
src/Writer/XmlWriter.php

I am targeting this branch, because it's just phpdoc.
`open` and `write` function can throws \RuntimeException. Let's warn about this.
When using a tool checking for try/catch, a wrong phpdoc give a weird behaviour.
Not needed for phpdoc

Add throw annotation

---

src/Source/DoctrineODMQuerySourceIterator.php
tests/Source/DoctrineODMQuerySourceIteratorTest.php

The ISO 8601 format is more common for dates.
I am targeting this branch, because this is a BC break.
```markdown
- Change default date format to ISO standard
```

Change default date format to ISO standard

---

src/Source/AbstractPropertySourceIterator.php
src/Source/DoctrineODMQuerySourceIterator.php
src/Source/DoctrineORMQuerySourceIterator.php
src/Source/PropelCollectionSourceIterator.php
tests/Source/DoctrineORMQuerySourceIteratorTest.php

I am targeting this branch, because BC.
Closes #31.
```markdown
- Added support for array and traversable in `DoctrineORMQuerySourceIterator`, `DoctrineODMQuerySourceIterator` and `PropelCollectionSourceIterator`.
```

Add support for array and traversable

---

UPGRADE-2.x.md
composer.json
docs/reference/symfony.rst
src/Bridge/Symfony/Bundle/SonataExporterBundle.php
src/Bridge/Symfony/SonataExporterBundle.php
src/Bridge/Symfony/SonataExporterSymfonyBundle.php

Add `SonataExporterSymfonyBundle` in order to be compatible with Symfony Flex.
I am targeting this branch, because these changes respect BC.
```markdown
- Added `Sonata\Exporter\Bridge\Symfony\SonataExporterBundle`.
- Added `Sonata\Exporter\Bridge\Symfony\SonataExporterSymfonyBundle` alias in order to fix Symfony Flex autodiscovery.
- Deprecated `Sonata\Exporter\Bridge\Symfony\Bundle\SonataExporterBundle` in favor of `Sonata\Exporter\Bridge\Symfony\SonataExporterBundle`.
```

Add `SonataExporterSymfonyBundle` in order to be compatible with Symfony Flex

---

composer.json
src/Bridge/Symfony/DependencyInjection/Configuration.php

Drop support for "symfony/*:<4.4".
I am targeting this branch, because these changes respect BC.
```markdown
- Removed support for "symfony/*:<4.4".
```

Drop support for "symfony/*:<4.4"

---

src/Source/AbstractPropertySourceIterator.php
src/Source/DoctrineDBALConnectionSourceIterator.php
src/Source/DoctrineODMQuerySourceIterator.php
src/Source/DoctrineORMQuerySourceIterator.php
src/Source/PropelCollectionSourceIterator.php

I am targeting this branch, because BC.
I allowed to use multiple times the `rewind` function for most of our SourceIterator.
Doctrine doesn't allow to call multiple times rewing, but since we're creating a new iterator, we just call rewing once on each iterator.
```markdown
- Add the ability to call the `rewind()` method multiple times for `DoctrineDBALConnectionSourceIterator`, `DoctrineODMQuerySourceIterator`, `DoctrineORMQuerySourceIterator`.
```

Improve rewind

---

composer.json
src/Source/DoctrineODMQuerySourceIterator.php

[`Query::iterate` was deprecated in `doctrine/mongo-odm` `1.3`](https://github.com/doctrine/mongodb-odm/blob/1.3.x/lib/Doctrine/ODM/MongoDB/Query/Query.php#L413).
I am targeting this branch, because these changes are BC.
```markdown
- Added conflict with `doctrine/mongodb-odm` <1.3
```

Fix DoctrineODMQuerySourceIterator

---

src/Source/DoctrineODMQuerySourceIterator.php
src/Source/DoctrineORMQuerySourceIterator.php

I am targeting this branch, because I've faced with BC break.
After refactoring source iterators here https://github.com/sonata-project/exporter/pull/343 there was lost detaching objects from object managers what led to memory leaks.
```markdown
- Memory leaks in Doctrine source iterators
```

Fix Doctrine source iterators

---

src/Bridge/Symfony/Bundle/SonataExporterBundle.php

Fix redeclared class at `Sonata\Exporter\Bridge\Symfony\Bundle\SonataExporterBundle`.
I am targeting this branch, because this change respects BC.
Bug introduced at #345.
```markdown
- Redeclared class `Sonata\Exporter\Bridge\Symfony\Bundle\SonataExporterBundle`.
```

Fix redeclared class at `Sonata\Exporter\Bridge\Symfony\Bundle\SonataExporterBundle`

---

src/Source/DoctrineODMQuerySourceIterator.php
tests/Source/DoctrineODMQuerySourceIteratorTest.php
tests/Source/Fixtures/Document.php

When using MongoDB, IterableResult::current() method returns the current document, not an array.
I am targeting this branch, because this is a bugfix.
Closes #452.
```markdown
- Fixed iterating over documents when using `DoctrineODMQuerySourceIterator`.
```
Can you please try it @webdevilopers?

Fix accessing the object as array

---

src/Source/AbstractPropertySourceIterator.php

I am targeting this branch, because patch.
For instance, Excel is handling differently string and float values ; so we should not restrict the value to be string.
```markdown
- Allow `AbstractPropertySourceIterator::getValue()` to return `bool|int|float` value.
```

Fix phpdoc of AbstractPropertySourceIterator::getValue

---

src/Source/DoctrineORMQuerySourceIterator.php
tests/Source/DoctrineORMQuerySourceIteratorTest.php
tests/Source/Fixtures/Entity.php

Clearing the entity manager at each result leads to very poor performances. Using a batch size of 100 seems reasonnable to keep good performances and memory under control.
I am targeting this branch, because it's a BC performance fix.
```markdown
- Clear entity manager every 100 results to improve ORM iterator performances
```

Improve ORM iterator performances

---

README.md

I am targeting this branch, because the only usage we have is for the standalone library directly using the writer.
However, we have a much more simple way to implement an export HTTP response thanks to the exporter service, but I see no example about it.

docs: symfony example with exporter
