sonata-project/exporter

composer.json

https://getcomposer.org/doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md

Require symfony/routing ~2.3

---

lib/Exporter/Writer/FormattedBoolWriter.php
test/Exporter/Test/Writer/FormattedBoolWriterTest.php

@OskarStark In response to my previous PR #50 , as proposed by @Soullivaneuh , 
I submit this new one.

Add FormattedBoolWriter

---

.php_cs
.travis.yml
composer.json

This PR adds symfony 3.0 support.

Symfony 3.0 support

---

.php_cs
lib/Exporter/Source/SymfonySitemapSourceIterator.php
test/Exporter/Test/HandlerTest.php
test/Exporter/Test/Source/ArraySourceIteratorTest.php
test/Exporter/Test/Source/ChainSourceIteratorTest.php
test/Exporter/Test/Source/CsvSourceIteratorTest.php
test/Exporter/Test/Source/IteratorCallbackSourceIteratorTest.php
test/Exporter/Test/Source/IteratorSourceIteratorTest.php
test/Exporter/Test/Source/PDOStatementSourceIteratorTest.php
test/Exporter/Test/Source/PropelCollectionSourceIteratorTest.php
test/Exporter/Test/Source/XmlExcelSourceIteratorTest.php
test/Exporter/Test/Source/XmlSourceIteratorTest.php
test/Exporter/Test/Writer/CsvWriterTest.php
test/Exporter/Test/Writer/GsaFeedWriterTest.php
test/Exporter/Test/Writer/JsonWriterTest.php
test/Exporter/Test/Writer/SitemapWriterTest.php
test/Exporter/Test/Writer/XlsWriterTest.php
test/Exporter/Test/Writer/XmlExcelWriterTest.php
test/Exporter/Test/Writer/XmlWriterTest.php

'header_comment' rule added and all files that doesn't contain the header have been fixed.

Add HeaderCommentFixer in .php_cs

---

CHANGELOG.md
UPGRADE-2.0.md
composer.json

As discussed on https://github.com/sonata-project/dev-kit/issues/51.

Bump Symfony support to 2.8

---

lib/Exporter/Handler.php
lib/Exporter/Source/AbstractXmlSourceIterator.php
lib/Exporter/Source/ArraySourceIterator.php
lib/Exporter/Source/ChainSourceIterator.php
lib/Exporter/Source/CsvSourceIterator.php
lib/Exporter/Source/DoctrineDBALConnectionSourceIterator.php
lib/Exporter/Source/DoctrineODMQuerySourceIterator.php
lib/Exporter/Source/DoctrineORMQuerySourceIterator.php
lib/Exporter/Source/IteratorCallbackSourceIterator.php
lib/Exporter/Source/IteratorSourceIterator.php
lib/Exporter/Source/PDOStatementSourceIterator.php
lib/Exporter/Source/PropelCollectionSourceIterator.php
lib/Exporter/Source/SymfonySitemapSourceIterator.php
lib/Exporter/Source/XmlSourceIterator.php
lib/Exporter/Writer/CsvWriter.php
lib/Exporter/Writer/InMemoryWriter.php
lib/Exporter/Writer/JsonWriter.php
lib/Exporter/Writer/XlsWriter.php
lib/Exporter/Writer/XmlExcelWriter.php
lib/Exporter/Writer/XmlWriter.php

```markdown
- Fixed wrong or missing PHPDoc
```
Some PHPDoc annotations are wrong or missing.

Fixed wrong or missing PHPDoc

---

test/Exporter/Test/Writer/CsvWriterTest.php
test/Exporter/Test/Writer/FormattedBoolWriterTest.php
test/Exporter/Test/Writer/GsaFeedWriterTest.php
test/Exporter/Test/Writer/JsonWriterTest.php
test/Exporter/Test/Writer/SitemapWriterTest.php
test/Exporter/Test/Writer/XlsWriterTest.php
test/Exporter/Test/Writer/XmlExcelWriterTest.php
test/Exporter/Test/Writer/XmlWriterTest.php

```markdown
- copy/paste mistake
```
Respect PSR-0

Declare actual namespace.

---

composer.json

Added all used dependencies for developers.
This will help while development, e.g. running code inspection.

Added missing dependencies for development

---

.github/ISSUE_TEMPLATE.md
.styleci.yml
.travis/install_docs.sh
CHANGELOG.md
CONTRIBUTING.md
UPGRADE-1.x.md
composer.json
docs/index.rst
docs/reference/symfony.rst
src/Bridge/Symfony/Bundle/SonataExporterBundle.php
src/Bridge/Symfony/DependencyInjection/Compiler/ExporterCompilerPass.php
src/Bridge/Symfony/DependencyInjection/Configuration.php
src/Bridge/Symfony/DependencyInjection/SonataExporterExtension.php
src/Bridge/Symfony/Resources/config/services.xml
src/Exporter.php
src/Test/AbstractTypedWriterTestCase.php
test/Bridge/Symfony/DependencyInjection/ConfigurationTest.php
test/Bridge/Symfony/DependencyInjection/ExporterCompilerPassTest.php
test/Bridge/Symfony/DependencyInjection/SonataExporterExtensionTest.php
test/ExporterTest.php
test/Writer/AbstractTypedWriterTestCase.php
test/Writer/CsvWriterTest.php
test/Writer/GsaFeedWriterTest.php
test/Writer/JsonWriterTest.php
test/Writer/SitemapWriterTest.php
test/Writer/XlsWriterTest.php
test/Writer/XmlWriterTest.php

I am targetting this branch, because this is a merge.
Refs https://github.com/sonata-project/dev-kit/issues/221

Merge 1.x manually

---

src/Source/IteratorCallbackSourceIterator.php
src/Writer/GsaFeedWriter.php
src/Writer/SitemapWriter.php

I am targetting this branch, because this is BC.
Fixes some PHPDoc

removed useless method comment 'Constructor.'

---

README.md

Fixed correct classname in README and add missing use statements.

Fixed correct classname in README and add missing use statements

---

composer.json
src/Bridge/Symfony/Bundle/SonataExporterBundle.php
src/Bridge/Symfony/DependencyInjection/Configuration.php
src/Exporter.php
src/Handler.php
src/Source/AbstractXmlSourceIterator.php
src/Source/CsvSourceIterator.php
src/Source/DoctrineODMQuerySourceIterator.php
src/Source/DoctrineORMQuerySourceIterator.php
src/Source/IteratorSourceIterator.php
src/Source/PropelCollectionSourceIterator.php
src/Source/SymfonySitemapSourceIterator.php
src/Source/XmlExcelSourceIterator.php
src/Source/XmlSourceIterator.php
src/Test/AbstractTypedWriterTestCase.php
src/Writer/CsvWriter.php
src/Writer/FormattedBoolWriter.php
src/Writer/GsaFeedWriter.php
src/Writer/InMemoryWriter.php
src/Writer/JsonWriter.php
src/Writer/SitemapWriter.php
src/Writer/TypedWriterInterface.php
src/Writer/XlsWriter.php
src/Writer/XmlExcelWriter.php
src/Writer/XmlWriter.php
test/Writer/CsvWriterTest.php
test/Writer/JsonWriterTest.php
test/Writer/XlsWriterTest.php
test/Writer/XmlWriterTest.php

I am targeting this branch, because this is a major BC-break.
```markdown
- PHP < 7.1 compatibility
```
Blocked by #142

Drop php 5

---

README.md

I am targeting this branch, because {reason}.
Closes #{put_issue_number_here}
```markdown
- Added some `Class::newMethod` to do great stuff
```

add documentation links

---

src/Source/DoctrineORMQuerySourceIterator.php
src/Source/PropelCollectionSourceIterator.php
src/Writer/XlsWriter.php
tests/ExporterTest.php
tests/HandlerTest.php
tests/Source/ArraySourceIteratorTest.php
tests/Source/ChainSourceIteratorTest.php
tests/Source/CsvSourceIteratorTest.php
tests/Source/IteratorCallbackSourceIteratorTest.php
tests/Source/IteratorSourceIteratorTest.php
tests/Source/PDOStatementSourceIteratorTest.php
tests/Source/PropelCollectionSourceIteratorTest.php
tests/Source/XmlExcelSourceIteratorTest.php
tests/Source/XmlSourceIteratorTest.php
tests/Writer/FormattedBoolWriterTest.php
tests/Writer/GsaFeedWriterTest.php
tests/Writer/SitemapWriterTest.php
tests/Writer/XmlExcelWriterTest.php

You know the drill. No merge, just approvals.

Manual merge

---

UPGRADE-2.0.md
composer.json
tests/Bridge/Symfony/DependencyInjection/ConfigurationTest.php
tests/Source/DoctrineORMQuerySourceIteratorTest.php
tests/Source/Fixtures/DoctrineORMQuerySourceIterator.php
tests/Source/Fixtures/ObjectWithToString.php

I am targeting this branch, because this is BC.
```markdown
- Dropped < Symfony3.4 dependencies
```

drop old dependencies

---

src/Exception/InvalidMethodCallException.php
src/Exception/SonataExporterException.php

I am targeting this branch, because this is BC.
```markdown
- Exception Marker
```

Exception Marker

---

src/Source/DoctrineORMQuerySourceIterator.php

This was recently merged into master, and should be the only piece of
code that needs to be modified before the next major release.

Use php 7 specific features in latest code

---

README.md
composer.json

Just approve this one, I will push it.

Bump version numbers

---

CHANGELOG.md
UPGRADE-2.0.md

Add missing CHANGELOG info

---

composer.json

Refs https://github.com/sonata-project/dev-kit/issues/10
I am targeting this branch, because this is pedantic.

Cleanup composer suggest section

---

tests/Source/IteratorSourceIteratorTest.php

New cs fixer rules, newly broken builds!

Adapt to new cs fixer rules

---

docs/reference/symfony.rst

fix bundle activation instruction

---

composer.json

I am targeting this branch, because it needs to be compatible with symfony 5.
```markdown
- Compatibility with Symfony 5
```

Symfony 5 allowed

---

README.md

I think we can stop talking about Symfony2 in the Readme 😄

Remove Symfony2 note

---

composer.json

```markdown
- Support for PHP8
```

Allow PHP8

---

composer.json

Bump dev dependency

---

src/Source/SourceIteratorInterface.php

BC
```markdown
- Added template typehint for SourceIteratorInterface
```

Add template for SourceIteratorInterface

---

src/Source/SourceIteratorInterface.php

See https://github.com/sonata-project/SonataAdminBundle/pull/6967/files#r601320490
```markdown
- Restrict `SourceIteratorInterface` template
```

Improve template
